#PATCH localhost:8080/feedback/13
#Content-Type: application/json

#{
#  "rating": 10,
#  "comments": ["I think it is a masterpiece"]
#}

#PATCH localhost:8080/purchase?id=8
#Content-Type: application/json

#GET localhost:8080/books/16
#Accept: application/json

#POST localhost:8080/books
#Content-Type: application/json#
#
#{
#    "id": "13",
#    "name": "Fairy Tale",
#    "author": "Stephen King",
#    "price": 64.99,
#    "rating": 7,
#    "comments": ["Sooo scary"],
#    "quantity": 4
#}